# Generated by Django 4.1 on 2022-12-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='title',
        ),
    ]
